### ISSUE TITLE
No module named 'supersqlite.third_party.internal.apsw'

### ISSUE THREAD

**Issue by pprados** [plasticityai/supersqlite#8]
Hello, I try to install supersqlite from pip and conda.
I can use
```
docker run -it ubuntu
# then
apt-get update ; \
apt-get install -y python-apsw python3 python3-pip ; \
pip3 install supersqlite ; python3 -c "import supersqlite"
```
It's correct.

Now, I try with conda

```
docker run -it conda/miniconda3
# Then
conda update conda -y ; \
conda init bash ;
exec bash
# and
conda install -c conda-forge apsw -y ; \
pip3 install supersqlite ; \
python3 -c "import supersqlite"
``` 
I receive and error:
`ModuleNotFoundError: No module named 'supersqlite.third_party.internal.apsw'`

```
Collecting supersqlite
  Downloading supersqlite-0.0.78.tar.gz (25.8 MB)
     |████████████████████████████████| 25.8 MB 3.9 MB/s 
Building wheels for collected packages: supersqlite
  Building wheel for supersqlite (setup.py) ... done
  Created wheel for supersqlite: filename=supersqlite-0.0.78-cp39-cp39-linux_x86_64.whl size=71094064 sha256=64d23d0848fba148a4506b0905135d23df4d7099660bbba683584b71623d38a2
  Stored in directory: /root/.cache/pip/wheels/c2/83/40/cffebda33928fae730f81985e5d75078d257db3586bd419905
Successfully built supersqlite
Installing collected packages: supersqlite
Successfully installed supersqlite-0.0.78
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/supersqlite/__init__.py", line 47, in <module>
    import supersqlite.third_party.internal.apsw as apsw
ModuleNotFoundError: No module named 'supersqlite.third_party.internal.apsw'
```

You can reproduce this bug with this docker file
```
# SuperSqliteDockerfile file
FROM continuumio/anaconda3

RUN conda create --name testSupersqlite python=3.7 ; \
    conda activate testSupersqlite ; \
    pip3 install supersqlite

ENTRYPOINT python -c "import supersqlite"
```
and
```
docker run --rm -it $(docker build -q -f SuperSqliteDockerfile .)
```
How can I resolve this problem?

Thanks

**Comment by wdduncan** [comment]
I have the same problem, even after install `apsw`.
